import os


def main():
    print("Welcome to ESIG HUB Setup! 🚀")
    print("--------------------------------")

    # 1. Ask for Frontend URL
    print("\n[CORS Configuration]")
    frontend_url = input(
        "Enter Frontend URL (e.g., http://localhost:8000) [Press Enter for *]: "
    ).strip()
    if not frontend_url:
        frontend_url = "*"

    # 2. Ask for GMS IP
    gms_ip = (
        input("Enter GMS IP Address [Default: 10.80.227.230]: ").strip()
        or "10.80.227.230"
    )

    # 3. Ask for Database Config
    print("\n[Database Configuration]")
    db_host = input("MySQL Host [Default: 127.0.0.1]: ").strip() or "127.0.0.1"
    db_port = input("MySQL Port [Default: 3306]: ").strip() or "3306"
    db_user = input("MySQL User [Default: root]: ").strip() or "root"
    db_pass = input("MySQL Password: ").strip()
    db_name = input("MySQL Database Name [Default: esig_hub]: ").strip() or "esig_hub"

    # Generate .env content
    env_content = f"""# ESIG HUB Configuration
# Generated by setup.py

# Server (SERVER)
BFF_HOST=0.0.0.0
BFF_PORT=1244
BFF_RELOAD=false
CORS_ORIGINS={frontend_url}

# GMS Legacy Socket (SERVICE)
GMS_IP={gms_ip}
GMS_PORT=24245
GMS_CLIENT_CODE=MEKTEC
GMS_CHANNEL_ID=11111

# Logging
LOG_LEVEL=INFO

# MySQL Database
DB_HOST={db_host}
DB_PORT={db_port}
DB_USER={db_user}
DB_PASS={db_pass}
DB_NAME={db_name}
"""

    with open(".env", "w", encoding="utf-8") as f:
        f.write(env_content)

    print("\n✅ Configuration saved to .env file!")
    print(f"   - CORS Allowed: {frontend_url}")
    print(f"   - GMS IP: {gms_ip}")
    print("\nYou can now run 'py main.py' to start the server.")


if __name__ == "__main__":
    main()
